### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by CberYellowstone** [cissusnar/KTier#2]
**平台**
e.g: Android | Windows

**需求描述**
能不能把支持的安卓系统降到7.0啊,现在还是有很多手机在运行7.0的
(技术上有什么困难?)

**解决了您的什么问题?**
很不幸,我的手机就是安卓7.0系统的..........

**附言**
如果开发者能实现这个需求,我就谢天谢地了

**Comment by cissusnar** [comment]
Android 切换到了 AndroidX框架， 一些依赖的库最低需求是Android 8.0. 
目前精力有限，只维护8.0以上的系统会节省一些精力，将来如果有时间会考虑再降低系统要求

**Comment by CberYellowstone** [comment]
那最后一个支持7.0的版本安装包可以给一下吗?谢谢

**Comment by cissusnar** [comment]
@CberYellowstone 最近几天会更新一个版本支持6.0以上机型
