### ISSUE TITLE
需求描述-增加PC端同步的快捷键

### ISSUE THREAD

**Issue by siwei-li** [cissusnar/KTier#28]
**平台**
Windows

**需求描述**
PC端除了窗口调出的快捷键外应再添加一个同步更新的快捷键。

**解决了您的什么问题?**
在不能随时刷新的情况，每次PC端和ios端互传时需要在PC端手动点击“同步剪切板”按钮，粘贴时相当于要先使用快捷键调出列表，点击更新按钮后再进行粘贴，这样无法发挥自定义快捷键实现handoff的精神，希望可以再加入一个更新的快捷键自定义。

**附言**

**Comment by cissusnar** [comment]
win 2.1.11 已修复不能自动同步的问题
