### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by phdbbs** [cissusnar/KTier#40]
**平台**
e.g: Android | 

**需求描述**
Android手机复制文本，还需要到应用里再去粘贴，才能同步。
不能监控剪贴板自动保存吗？

**解决了您的什么问题?**
手机上减少操作次数的问题。

**附言**
是不是我设置的不对？
为何不能像Mac上，复制即保存且同步。

**Comment by cissusnar** [comment]
从Android 10(Q)版本开始, 不允许应用后台读取剪贴板数据, 只能前台点击按钮才能读取

**Comment by phdbbs** [comment]
这个是需要什么授予什么特殊权限吗？
我看讯飞输入法都能记录剪贴板。
另外 全能分词 也是能自动记录安卓手机剪贴板，不需要一条条的添加。

在 2020年4月1日星期三，isaac zhang <notifications@github.com> 写道：
