### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by Nover2** [cissusnar/KTier#5]
**平台**
Android, Windows, iOS

**需求描述**
可以部署在自己的服务器，登录时选择登录到服务器

**解决了您的什么问题?**
同步速度快，保证隐私安全，减轻官方服务器压力

**附言**

**Comment by cissusnar** [comment]
后面会考虑增加自定义云盘, 不过自定义云盘不提供端对端加密

**Comment by Nover2** [comment]
> 
> 
> 感谢反馈, 后面会考虑增加自定义云盘, 不过自定义云盘不提供端对端加密

好的，感谢回复
