### ISSUE TITLE
希望推出会员收费

### ISSUE THREAD

**Issue by PHCSJC** [cissusnar/KTier#51]
发现在IOS端好像有广告，希望推出会员，最好的一次性的那种，比如68元永久会员，可以免广告，再加一些会员专属的功能，比如非会员只能3个终端同步，会员无限制。

**Comment by PHCSJC** [comment]
好的软件就应该有回报！

**Comment by cissusnar** [comment]
感谢反馈, 快贴现有功能会永久免费, 后面会推出一些增值服务 :)
