### ISSUE TITLE
Mac端插件商店无法添加插件，只能从官网下载导入

### ISSUE THREAD

**Issue by Blinhouang** [cissusnar/KTier#53]
**BUG描述**
Mac端插件商店无法添加插件，只能从官网下载导入

**截屏**

**桌面版:**
 - 系统版本: [e.g. macOS 10.15
 - 快贴版本 [e.g. 2.1.0]

**Comment by cissusnar** [comment]
感谢反馈, 这个问题会排查一下, 下个版本修复

**Comment by cissusnar** [comment]
2.1.7已修复
