### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by weiLanhao** [cissusnar/KTier#55]
**平台**
e.g: Android | Windows

**需求描述**
手机剪贴板自动同步到电脑剪贴板，而不是现在这样，需要先打开菜单，点击「同步剪贴板」，然后又打开菜单，才能选择「复制并粘贴」，流程过于繁琐。

**解决了您的什么问题?**
主要使用场景是在电脑上使用手机号和验证码登录，通常手机收到验证码时，系统会直接提供复制验证码的功能，如果可以在电脑上直接粘贴验证码，会方便很多。

**附言**

**Comment by cissusnar** [comment]
Windows和Mac版本的快贴可以在设置里面打开‘自动设置剪贴板’这个选项, 就可以自动同步到系统剪贴板了.

**Comment by weiLanhao** [comment]
那这就不是需求而是bug啦。。实测它就是不能自动同步啊。。。

**Comment by weiLanhao** [comment]
> Windows和Mac版本的快贴可以在设置里面打开‘自动设置剪贴板’这个选项, 就可以自动同步到系统剪贴板了.

那这就不是需求而是bug啦。。实测它就是不能自动同步啊。。。
