### ISSUE TITLE
报告BUG

### ISSUE THREAD

**Issue by momorans** [cissusnar/KTier#6]
**BUG描述**
MAC和windows端 无法同步图片

**如何复现**
1. 
2. 
3. 

**截屏**

**桌面版:**
 - 系统版本: [macOS 10.15 
- Windows 10 build 1883]

mac快贴版本2.1.1
windows快贴版本2.1.2 

升级后才这样上一个版本是可以同步的

**手机版:**
 - 设备: [e.g. iPhone6 | pixel 3a]
 - 系统版本: [e.g. iOS8.1 | Android 8]
 - 快贴版本 [e.g. 2.1.1]

**附言**
...

**Comment by cissusnar** [comment]
win10上目前有一些问题, 正在积极修复, 感谢反馈

**Comment by cissusnar** [comment]
Windows版快贴2.1.7版本已修复
