### ISSUE TITLE
报告BUG window剪切板同步问题

### ISSUE THREAD

**Issue by vcjmhg** [cissusnar/KTier#7]
**BUG描述**
Android端和ios端可以正常进行剪切板的同步操作，并且同步内容可以正常显示到window端（win7），但是window端（win7）剪切板的内容无法正常同步到云端上面

**如何复现**
1.在win7端复制任意内容都无法同步到其他端应用上

**截屏**
![设置](https://user-images.githubusercontent.com/55177318/68521627-e3237080-02dd-11ea-8899-7c93e5099487.png)

![pc端图片](https://user-images.githubusercontent.com/55177318/68521623-de5ebc80-02dd-11ea-94d8-8ee2e15d2bd2.png)
![android端快贴](https://user-images.githubusercontent.com/55177318/68521625-df8fe980-02dd-11ea-9c10-ddb06e5dc94b.jpg)

**桌面版:**
 - 系统版本: Windows 7
 - 快贴版本 2.1.2

**附言**
也可能是我自己电脑设置的问题，但我实在想不到解决问题，我尝试过将防火墙关闭但依然没有效果

**Comment by cissusnar** [comment]
win版现在有一个已知bug, 这里会尽快发布一个新版本

**Comment by cissusnar** [comment]
2.1.7版本已修复
